AWSTemplateFormatVersion: 2010-09-09
Description: "This template will spawn simple ES2 instance."
Parameters:
   instanceType:
      AllowedValues:
         - t1.micro
         - t1.nano
         - t2.micro
         - t2.small
      ConstraintDescription: "must be a valid EC2 instance type."
      Default: "t1.nano"
      Description: "WebServer EC2 instance type"
      Type: "String"

   sshKey:
      Description: "Name of an existing EC2 KeyPair to enable SSH access to the instances"
      ConstraintDescription: "must be the name of an existing EC2 KeyPair."
      Type: AWS::EC2::KeyPair::KeyName
      Default: "hertzner"

Resources:
   simpleInstance:
      Type: AWS::EC2::Instance
      Properties:
         ImageId: "ami-0ca467408e84df23c"
         InstanceType: !Ref instanceType
         KeyName: !Ref sshKey

Outputs:
   publicIp:
      Description: EC2 public IP
      Value: !GetAtt instanceType.PublicIp